// <auto-generated />
using DataProcessorService.Storage.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataProcessorService.Migrations
{
    [DbContext(typeof(Module_SqliteContext))]
    [Migration("20251008103636_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DataProcessorService.Storage.Models.Modules", b =>
                {
                    b.Property<string>("ModuleCategoryID")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuleState")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModuleCategoryID");

                    b.ToTable("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
